### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [mbikovitsky/AssemblyBot#1]
oh this is so cool! do you have any screenshot for this?

cheers.

**Comment by mbikovitsky** [comment]
Very nice to hear that! Thank you.
I uploaded some screenshots.

**Comment by aquynh** [comment]
that is awesome! linked to your project from our websites now: http://www.keystone-engine.org/showcase/ & http://www.capstone-engine.org/showcase.html

keep it up!
